spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      #配置WebStatFilter
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
        session-stat-enable: true
        profile-enable: true
        principal-session-name: org.apache.shiro.subject.support.DefaultSubjectContext_PRINCIPALS_SESSION_KEY
      #配置StatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #是否允许重置数据
        reset-enable: false
        #白名单
        #allow: 127.0.0.1
        #黑名单，优先级高于白名单
        #deny: 192.168.1.11
        #login-username: root
        #login-password: root

  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*/*.xml

mapper:
  mappers: cn.inslee.admin.model.base.BaseMapper
  identity: MYSQL